# Generated by Django 3.2.9 on 2022-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('date_naiss', models.DateField()),
                ('sexe', models.CharField(max_length=2)),
                ('telephone', models.CharField(max_length=20)),
                ('date_sous', models.DateField()),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
            ],
        ),
    ]
